### ISSUE TITLE
error while running main.py

### ISSUE THREAD

**Issue by pradeepkc11** [noorchauhan/DeepFake-Audio-Detection-MFCC#4]
i have copied real audio in real_audio folder and fake audio in fake audio folder and i ran as given by you this is the error i got
Traceback (most recent call last):
  File "/home/pradeep/DeepFake-Audio-Detection-MFCC/main.py", line 135, in <module>
    main()
  File "/home/pradeep/DeepFake-Audio-Detection-MFCC/main.py", line 132, in main
    train_model(X, y)
  File "/home/pradeep/DeepFake-Audio-Detection-MFCC/main.py", line 42, in train_model
    raise ValueError("Atleast 2 set is required to train")
ValueError: Atleast 2 set is required to train

**Comment by noorchauhan** [comment]
Please set proper locations in the main.py file for your path to which you have audio files in, please go through the code before running and make sure your path is updated accordingly
